project:
  type: website

website:
  title: "Alexander's data science website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Assignments"
        menu:
          - ae03-gerrymander.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - about.qmd
      - section: "Assignments"
        contents:
          - ae03-gerrymander.qmd

format:
  html:
    theme:
      - lumen
      - brand
    css: styles.css
    toc: true



